Homework-30
Otus-DevOps-2017-11/nefariusmag_microservices pull request #13
Opened 2018-03-30 12:20 UTC by Nefariusmag

Посмотрите домашку плиз.

Не совсем понял разницу в PersistentVolume и PersistentVolumeClaim на бытовом уровне((

2018-03-30 13:13 UTC, Nefariusmag commented
И почему-то у меня Ingress не ставился иногда по команде. Не понял до конца почему.

2018-04-09 18:12 UTC, Nefariusmag commented
Подмержил мастер, чтобы меньше диф был

2018-04-12 07:14 UTC, chromko requested changes
1) Поправь пожалуйста в дз, чтобы было красиво) 
2) Ответы на вопросы:
- Ingress долго отдупляет на gcp - из-за хелсчеков для эндпоинтов, которые он проводит периодически. Это специфика именно gcp. Если ставить свой ingress (например, nginx), то там все будет практически мгновенно срабатывать

- По разнице между PV и PVC. 
PV - это реальный объект хранилища (т.е. допустим 25 Гб определенного качества в определенном кластере, выделяемых нашему кластеру, когда мы этот PV создаем, которыми мы можем пользоваться)
PVC - это ЗАПРОС на создание/использование такого объекта. Т.е. самого объема доступной памяти нам могут и не дать, но запрос будет висеть, пока не будет доступен запрашиваемый ресурс. При подаче ЗАЯВКИ в виде PVC нам должны выделить соответствующий PV, уже которым мы можем пользоваться ( в деплойменте монги мы говорим, что хотим использовать то, хранилище, которое по заявке будет выдано).
Если  не понятно - задавай вопросы, разберем подробнее.

2018-04-12 07:14 UTC, chromko commented on kubernetes/ui-service.yml
> +  type: LoadBalancer
Тут нам уже не обязательно LoadBalancer выделять. У нас есть Ingress в качестве точки входа в кластер. Типа NodePort уже хватает.

2018-04-12 07:14 UTC, chromko commented on kubernetes/tls.key
> +-----BEGIN PRIVATE KEY-----
Ключи и сертификаты не следует публиковать в репозиториях.
В идеале в `.gitignore` сразу добавлять записи вроде `*.key` , `*.crt` , `.*pem` ,... 
А сам .gitignore по-дефолту добавлять во все проекты. 
Это защитит от случайных публикаций секретов

2018-04-12 12:58 UTC, Nefariusmag commented
Я поправил, а как мне теперь правильно получить одобрение? Удалить этот и создать новый мерж?

2018-04-12 19:50 UTC, chromko approved these changes
нет, я просто одобряю изменения)
Все ок. Вопросов я так понимаю нет больше по заданию?

2018-04-13 11:10 UTC, Nefariusmag commented
PVC и PV более менее понятно, а дальше в жизни посмотрю понадобиться ли.

Спасибо

2018-04-13 11:10 UTC, merged